In [26]:
import numpy as np
import time
import random

In [3]:
mid_score = [10, 20, 30]
final_score = [70, 80, 90]
total_score = (np.array(mid_score) + np.array(final_score))
print("시험 합계:",total_score,"\n시험평균:", total_score/2)

시험 합계: [ 80 100 120] 
시험평균: [40. 50. 60.]


In [5]:
a = np.array(range(1,11))
b = np.array(range(10,101,10))
print(f"a + b = {a+b}\na - b = {a-b}\na * b = {a*b}\na / b = {a/b}\n")

a + b = [ 11  22  33  44  55  66  77  88  99 110]
a - b = [ -9 -18 -27 -36 -45 -54 -63 -72 -81 -90]
a * b = [  10   40   90  160  250  360  490  640  810 1000]
a / b = [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]



In [13]:
a = np.array([range(1,11)])
print(a.size
,a.dtype
,a.shape
,a.ndim)
b = range(100)
b

10 int64 (1, 10) 2


range(0, 100)

In [15]:
salary = np.array([220,250,230])
salary = salary + 100
print(salary)

[320 350 330]


In [16]:
lst = [199,"test",3.00, False]
tangled = np.array(lst)
print(tangled)

['199' 'test' '3.0' 'False']


In [25]:
def factorial_l(n):

  s = sum(range(n+1))
  return s

def factorial_a(n):

  s = sum(np.arange(1,n+1))

  return s

startl = time.time()
l = factorial_l(100)
endl = time.time()

start = time.time()
a = factorial_a(100)
end = time.time()
print(f"list 실행시간: {end-start}\n arr 실행시간: {endl-startl}",
      f"\nlist 실행 결과: {l}\n arr 실행 결과: {a}")

list 실행시간: 0.0001518726348876953
 arr 실행시간: 5.5789947509765625e-05 
list 실행 결과: 5050
 arr 실행 결과: 5050


In [ ]:
li = range(10)
arr = np.arrary(li)


In [41]:
heights = []
weights = []
while len(heights)<10:
  heights.append(random.randrange(140,200))
  weights.append(random.randint(40,100))
heights = np.array(heights)
heights = heights/100
weights = np.array(weights)
bmi = weights/heights**2
print(bmi)
print("비만:", bmi[bmi>25])
print(heights)


[27.34375    22.59143813 23.44934084 40.88888889 27.15271059 26.10656224
 29.02531132 44.50095359 14.37717014 13.73240536]
비만: [27.34375    40.88888889 27.15271059 26.10656224 29.02531132 44.50095359]
[1.6  1.87 1.87 1.5  1.79 1.59 1.79 1.43 1.92 1.79]


In [40]:
score = [69,34,55,79,90,57,92,59,69,77]
arr = np.array(score)
print(arr[arr>70])

[79 90 92 77]


# 인덱싱과 슬라이싱도 쓸 수 있다.

## 논리적인 인덱싱


In [43]:
ages = np.array([18,19,25,30,28])
print(ages[1:3])
print(ages[ages>20]) ## 논리 연산자를 통한 출력
## 관계 식이 True 인 인덱스의 요소만 출력
print(ages<20)

[19 25]
[25 30 28]
[ True  True False False False]


In [60]:
a = np.arange(1,17).reshape(4,4)
print(a, a.size)
print(a[:3,:3])
print(a[1:3,1:3])
print(a[::2,::2])
print(a[a>10]) # lohical indexing 하면 1차원으로 바뀜

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 16
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]
[11 12 13 14 15 16]
